### ISSUE TITLE
qiuckstart

### ISSUE THREAD

**Issue by fangxunyes** [chenzhaiyu/abspy#17]
Hi, I follow the your steps to install the packages but failed to run the quick start code. 
I use your test data ‘test_points.vg’
It shows 'NameError: name 'bounds' is not defined'
![1667836011343](https://user-images.githubusercontent.com/109592560/200354564-ab6d2fbe-9a11-4c16-a1ef-99dcaaf33ed3.jpg)

then I add ‘from trimesh import bounds’
but it shows ‘TypeError: 'module' object is not subscriptable’
![1667836479358](https://user-images.githubusercontent.com/109592560/200355148-9fe8fa90-56be-4af3-9fa1-87805794cabf.jpg)

this are my environment
ubuntu 20.04
python=3.9.13
abspy=0.2.1
sage=9.4
others are installed by ‘pip install -r requirements’

Can I get any tips? thank you

**Comment by chenzhaiyu** [comment]
Hi @fangxunyes, here `bounds` is just some arbitrary placeholder representing the bounding box of the geometry (hence `bounds[:, 0, 2]` means the minimal Z-value, therefore `additional_planes` to append here actually represents the bottom plane of the geometry). You can assign any plane parameters to `additional_planes`, e.g.,
```python
additional_planes = [[0, 1, 2, 3], [100, 200, 300, -500]]
```
You can get some idea by checking [test_primitive](https://github.com/chenzhaiyu/abspy/blob/main/tests/test_primitive.py) and [test_combined](https://github.com/chenzhaiyu/abspy/blob/main/tests/test_combined.py).
