### ISSUE TITLE
ValueError: No such backend xxx implemented for given basering (=Integer Ring).

### ISSUE THREAD

**Issue by yqf2000119** [chenzhaiyu/abspy#19]
hi, i got a bug when i try to run the 'quick start' code from github

the bug is happened when called the function CellComplex from complex.py in abspy.   it seems like the problem is sagemath but i am not sure. 

1. Input 'test_points.vg' download with abspy

2. See error: No such backend (=[[-73955476/123260931, 29460755/49106297], [-30488850/110333459, 57316241/207374152], [-31705399/335534790, 31705409/335534790]]) implemented for given basering (=Integer Ring).

**Screenshots**
![2023-09-25 214727](https://github.com/chenzhaiyu/abspy/assets/58506495/3c7aaf82-706f-400a-8aff-893707f161c0)

**Additional context**
     my sage version is 9.0 and the abspy version is 0.2.3

**Comment by chenzhaiyu** [comment]
Hi @yqf2000119, can you please upgrade sage to version 9.4 and try again? I guess 9.0 is too old. See also https://github.com/chenzhaiyu/abspy/issues/13.

**Comment by yqf2000119** [comment]
> Hi @yqf2000119, can you please upgrade sage to version 9.4 and try again? I guess 9.0 is too old. See also #13.

thanks for your reply，I will try to upgrade sage to verison 9.4 and run the code again.

**Comment by chenzhaiyu** [comment]
The error message explains for itself. This is not a bug, but rather that your provided initial bound is wrong. This should be irrelevant to the WSL or Ubuntu version. Did you bump into the error with any of the test_xx.py files or your own?

**Comment by yqf2000119** [comment]
> 错误消息本身解释了。这不是错误，而是您提供的初始边界是错误的。这应该与 WSL 或 Ubuntu 版本无关。您是否遇到任何test_xx.py文件或您自己的文件的错误？

thanks for your reply, I did not encounter any errors with the xx.py file. I looked back and found that I did not take screenshots to output the results. One possible issue currently is the VG file I am using, which is test.points.vg under the test directory in the abspy directory.
this is the output，its report a warning。
![屏幕截图 2023-09-27 091601](https://github.com/chenzhaiyu/abspy/assets/58506495/ed48f50a-8a5a-4d50-bb52-79b660c85390)

**Comment by chenzhaiyu** [comment]
The warning is an expected behavior when you provide additional planes and refine planes. Those additional planes are not part of the refinement.

**Comment by yqf2000119** [comment]
> 该警告是提供其他平面和优化平面时的预期行为。这些额外的飞机不是改进的一部分。



> Owner
> ###



> The warning is an expected behavior when you provide additional planes and refine planes. Those additional planes are not part of the refinement.

thanks for your reply, I think I know what my problem is now
